// <auto-generated />
namespace Envision.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class descriptionproptoticket_cs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(descriptionproptoticket_cs));
        
        string IMigrationMetadata.Id
        {
            get { return "201508060034183_description prop to ticket_cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
